### ISSUE TITLE
Error during install- EXTERN.h missing

### ISSUE THREAD

**Issue by t-carroll** [egaffo/mirandmore2#2]
Hi there,

Excited to give this tool a shot, but encountering some difficulties with the installation process. This may be compounded by the fact that I don't have sudo access on our group's cluster, but tried my best to install the appropriate dependencies through conda/locally. The error I'm encountering is thrown after cloning the repository and running the install script; I copy the relevant output below. It looks like one of the build steps involving Perl is looking for an EXTERN.h file that doesn't exist/isn't created when I try to install. Could you let me know what you think? I'm on a CentOS Linux 7 HPC, if that's helpful.

`./install_mnm2`

> ..........
/users/tcarroll/sharedscratch/bin/git/mirandmore2
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
cd `dirname tools/ViennaRNA-2.4.14/Makefile` && make -j
make  all-recursive
make[1]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14'
Making all in src
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src'
Making all in ViennaRNA
make[3]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA'
Making all in static
make[4]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA/static'
make  all-am
make[5]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA/static'
make[5]: Nothing to be done for `all-am'.
make[5]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA/static'
make[4]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA/static'
make[4]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA'
make[4]: Nothing to be done for `all-am'.
make[4]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA'
make[3]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/ViennaRNA'
Making all in bin
make[3]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/bin'
  CCLD     RNAfold
make[3]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/bin'
Making all in Utils
make[3]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/Utils'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src/Utils'
make[3]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src'
make[3]: Nothing to be done for `all-am'.
make[3]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src'
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/src'
Making all in man
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/man'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/man'
Making all in misc
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/misc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/misc'
Making all in doc
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/doc'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/doc'
Making all in RNA-Tutorial
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/RNA-Tutorial'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/RNA-Tutorial'
Making all in interfaces
make[2]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/interfaces'
Making all in Perl
make[3]: Entering directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/interfaces/Perl'
  CXX      RNA_la-RNA_wrap.lo
RNA_wrap.cpp:762:20: fatal error: EXTERN.h: No such file or directory
 #include "EXTERN.h"
                    ^
compilation terminated.
make[3]: *** [RNA_la-RNA_wrap.lo] Error 1
make[3]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/interfaces/Perl'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14/interfaces'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/mnt/lustre/users/tcarroll/bin/git/mirandmore2/tools/ViennaRNA-2.4.14'
make: *** [all] Error 2
scons: *** [tools/ViennaRNA-2.4.14/src/bin/RNAfold] Error 2
scons: building terminated because of errors.

**Comment by egaffo** [comment]
That is a problem related to the [ViennaRNA package ](tbi.univie.ac.at/RNA/documentation.html#install). 
You missed the perl-devel package in your system. 
I tested on a centos7 docker image and after 
`yum install perl-devel `
the ViennaRNA package compliled without errors.
Ask your sysadmin to install it.

**Comment by t-carroll** [comment]
Sorry just circling back to this now- waiting on admin for perl-devel, but was able to get a workaround local solution up and running by installing ViennaRNA from Conda. Thanks for the help!
