### ISSUE TITLE
Error due to duplicate precursor-name

### ISSUE THREAD

**Issue by vivekruhela** [egaffo/mirandmore2#3]
While running mirandmore2 pipeline on my data, I have  got the following error:

    Negative repeat count does nothing at /mnt/disk2/Mirpipe/mirandmore2/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 4192087.
    Negative repeat count does nothing at /mnt/disk2/Mirpipe/mirandmore2/bin/miRDeep2_core_algorithm.pl line 1458, <FILENAME> line 5548059.
    [fai_build_core] ignoring duplicate sequence "hsa-mir-6511b-1-ext" at byte offset 150195
    WARNING: duplicated precursorname for hsa-mir-6511b-1-ext. Will change into hsa-mir-6511b-1-ext|MI0022552_2
    Traceback (most recent call last):
      File "/mnt/disk2/Mirpipe/mirandmore2/bin/gff2maturetable.py", line 225, in <module>
        gff2maturetable([args.mature_table], [args.gff], env)
      File "/mnt/disk2/Mirpipe/mirandmore2/bin/gff2maturetable.py", line 56, in gff2maturetable
        mirna_pre_id = re.findall(r'Derives_from=([^;]*)',items[8])[0].strip()
    IndexError: list index out of range
    scons: *** [mirandmore_dbs/annotation_files/extended_annotation/mature-table.txt] Error 1

Unfortunately, I am not able to understand why this error occurred and how to debug. Need suggestions. Thanks.

**Comment by egaffo** [comment]
It seems you have duplicated entry in your annotation file for hsa-mir-6511b-1 .
Can you check that?

**Comment by vivekruhela** [comment]
Ok. I checked annotation file and corrected. Thanks.
